### ISSUE TITLE
adding distance and linkage method options

### ISSUE THREAD

**Issue by crazyhottommy** [Bohdan-Khomtchouk/shinyheatmap#1]
Hi,

Different distance measure and linkage method can have different effect on the looking of the heatmap. you may want to add those as options. 

see write-ups by me https://rpubs.com/crazyhottommy/PCA_MDS  
https://rpubs.com/crazyhottommy/a-tale-of-two-heatmap-functions  

I also made a simple shiny app for choosing linkage https://divingintogeneticsandgenomics.shinyapps.io/shiny_App/

Thanks!
Tommy

**Comment by Bohdan-Khomtchouk** [comment]
Hi Tommy,

Thanks for these links!  Why don't you create a pull request and I can add you as a contributor?  I'm so swamped with other projects at the moment (the bioinformaticians' dilemma)... :-)

Cheers,
Bohdan

**Comment by crazyhottommy** [comment]
I am not very experienced with shiny...I just finished the simple one for one course.
I am current too busy as well as a computational biologist, but will see what I can help with this.

Best,
Tommy
