### ISSUE TITLE
saving from R as svg

### ISSUE THREAD

**Issue by ccr25** [Bohdan-Khomtchouk/shinyheatmap#10]
I am running the developer version, I have the option to download as an html. Is there a way to download as another file type in R? Thanks, 

Chandler

**Comment by Bohdan-Khomtchouk** [comment]
Hi Chandler,

Thanks for your note.  You'll need to provide more detail on what you're trying to achieve.  You already have the option to download as PNG.

Best,
Bohdan

**Comment by Bohdan-Khomtchouk** [comment]
Closing this for now.  Please re-open if the issue is still unresolved.
